### ISSUE TITLE
Introduce support for ES256K with secp256k1 curve for signing \ veryfying JWT tokens.

### ISSUE THREAD

**Issue by eshepelyuk** [lestrrat-go/jwx#334] opened 2021-02-16 10:19 UTC
**Abstract**  \ **Additional context**

As a user of [Open Policy Agent](https://www.openpolicyagent.org/) I want to be able to use ES256K with secp256k1 to sign \ verify JWT tokens in REGO policies. 
Open Policy Agent uses `jwx` as a backing technology, so the question is addressed here.

**Comment by lestrrat** [comment] 2021-02-16 13:42
I'm not familiar with with this algorithm, so... PRs welcome

**Comment by eshepelyuk** [comment] 2021-02-16 14:02
Hello

I'm not familar with Golang and Cryptography at all, so PR from my side will not be delivered.
If you're willing to keep this issue open - then let more experienced guys to implement it it some future, maybe.
Otherwise, it could be closed.

Thnx

**Comment by imirkin** [comment] 2021-02-16 15:17
It seems like the canonical secp256k1 implementation is in go-ethereum.

https://pkg.go.dev/github.com/ethereum/go-ethereum/crypto/secp256k1

@lestrrat if you think it's reasonable to depend on this package, I can give this a go.

**Comment by lestrrat** [comment] 2021-02-16 15:23
@imirkin i was actually looking at https://github.com/decred/dcrd/tree/master/dcrec/secp256k1

from what I could tell if we use ethereum-go or btcd 's implementation you would have to import the entire app, which is... meh

anyway that's all i had time to research. will check back tomorrow morning

**Comment by imirkin** [comment] 2021-02-16 15:34
@lestrrat Hm, yeah, there's no go.mod file there. Annoying. It wraps libsecp256k1 though, which hopefully gives the implementation some credibility.

My more general concern is with depending on encryption from "weird" places. Thus far, we depend on core lib and x/crypto, which is as non-weird as it gets. I've never heard of decred -- perhaps it's a huge project which gets security audits and whatnot, but that should be confirmed. I've heard of ethereum, and the fact that it's just a libsecp256k1 wrapper makes me a bit more comfortable. There are a few other places that wrap libsecp256k1, and it's not a ton of code and should be importable into jwx directly if need be (looks like a BSD license on the core lib).

I believe the Go maintainers' position is that secp256k1 is an esoteric curve only used for blockchains, so it's unlikely to make it to the main libraries. (Similar to x448.)

**Comment by lestrrat** [comment] 2021-02-16 15:40
my initial reaction is that i would rather not use a C implementation out of concerns from a support perspective.

that library i linked up there seems to be pure Go, which is why was reading up on it

I'm now turning off my phone. will cehck tomorrow! :)

**Comment by imirkin** [comment] 2021-02-16 19:21
OK, well, up to you. Certainly a pure-go implementation is preferable. But I'm sure you've heard the advice about not rolling your own encryption primitives -- so the question is whether the people implementing the pure-go version are exempt from this advice (someone somewhere has to be, or else we wouldn't have encryption) :)

**Comment by lestrrat** [comment] 2021-02-16 21:48
@imirkin Yeah, I hear you. It's a tough call, but this library is full of sinners (mainly me) so... I dunno, I can't pretend like I'm all innocent while we condemn people reinventing encryption wheels :)

The author of `decred` thing above at least has enough cryptocurrency experience under his belt. He is a major contributor to a [btcd alternative written in Go](https://github.com/btcsuite/btcd), so I think he's as good as it gets? The only thing that bugs me is that I so far can't find something equivalent to `jose` tool where we can create arbitrary signed values  for testing in an easy manner.

Anyways, @imirkin if you would like to do more investigation, my request is:

* It should be a standalone library -- no importing btcd or go-ethereum please.
* *preferably* it should be pure-Go
   * but am willing to go with a C-based implementation provided that at the end we make it an opt-in feature
   
(as a tangent, the lasts item above made me think: how can we make jwx "pluggable" -- so that we can add support for certain algorithms _only_ when libraries are imported, like "database/sql")

**Comment by cloudkucooland** [comment] 2021-02-16 21:57
It's not a sin to re-implement a known algorithm in a different language. It's only a sin to invent a new algorithm and imagine that it is secure w/o serious peer review.

So long as the new implementation gives the same results as the reference implementations, it is fine.

**Comment by imirkin** [comment] 2021-02-16 22:05
@cloudkucooland good luck proving that it gives the same results as the reference implementation... that tends to be the main problem. I guess my main point is that such things should not be done lightly.

@lestrrat FWIW there were no EdDSA tests either for the same reason when I added it (or X25519). I didn't feel great about it, but ... what are you gonna do. There's a node-based 'jose' tool which has it all (including like 100gb of dependencies). I agree on the opt-in stuff, I'm not sure what the best way to manage it is. I don't plan on doing the investigation though (into either other libraries or how to make stuff pluggable).

**Comment by lestrrat** [comment] 2021-02-16 22:15
@cloudkucooland what @imirkin said

@imirkin Don't worry about the pluggable stuff. The pluggable stuff sounds like a nightmare, and if/when we do it, it would be for the next API breaking release, far in the future.

If you are interested in doing the libsecp256k1 wrapper, go for it. Again, just not the whole ehtereum or btcd, please. Otherwise we shall wait for somebody with more knowledge on this subject.

**Comment by lestrrat** [comment] 2021-02-16 22:34
Oh wow, I just had a look at Open Policy Agent, and they not only fork jwx, they keep their local copy in the `internal` directory... If we ever do support ES256K, good luck using our changes @eshepelyuk, because the upgrade is going to be a nightmare.

**Comment by lestrrat** [comment] 2021-02-16 23:04
@imirkin Oh duh, re: pluggable stuff, I forgot I implemented this exact feature for JWS, at least !

https://github.com/lestrrat-go/jwx/blob/c6022d3ff13e1e18cb4977d63fd800cb76e5491e/jws/signer.go#L56-L58

I still would need to think about how to realize this for jwk and jwe, but in principle, something like this should work.

**Comment by imirkin** [comment] 2021-02-16 23:19
@lestrrat This (ES256K) only matters for jws -- it's only a signing algorithm. I'm not sure how the pluggability translates into optional dependencies. I guess you're thinking of adding build flags?

**Comment by lestrrat** [comment] 2021-02-16 23:40
@imirkin initially, yes on build flags.

```
go build -tags jwx_es256k ...
```

But now that I remembered about RegisterSigner(), I think it can even be a separate module all together (though not a requirement)

```go
//pseudocode
import (
   "github.com/lestrrat-go/jwx/jws"
   "github.com/imirkin/es256k"
)

func init() {
   jws.RegisterSigner("ES256K", es256k.Signer())
}
```

**Comment by lestrrat** [comment] 2021-02-16 23:41
BTW, if we're using tags, I don't really care about extra dependencies (though I care about *BIG* extra dependencies).
What I want to avoid is people claiming they can't compile the C backend and filing issues against this repo :)

**Comment by imirkin** [comment] 2021-02-17 14:47
So ... there's another thing to consider. The EC library in golang allows you to specify arbitrary curves. Only some have optimized implementations, but if you're happy with "slow", then you can just define your own CurveParams. I don't think I realized this before.

This may be sufficient for signing / verifying. What do you think?

I did a bit of further research on bitcoin's libsecp256k1 -- that library doesn't have any releases upstream, so it's tricky to depend on.

**Comment by imirkin** [comment] 2021-02-17 15:20
Of course the downside of that is that it's a non-deterministic algorithm, so verification could be subject to timing attacks. Sigh.

**Comment by imirkin** [comment] 2021-02-17 15:32
Looks like go-jose has an open issue and PR for this:

https://github.com/square/go-jose/issues/263
https://github.com/square/go-jose/pull/278

and they're looking at the decred impl. Perhaps it's the way to go.

**Comment by lestrrat** [comment] 2021-02-17 22:01
Yes, go-jose is where I found decred.

re: CurveParam, I did read up on CurveParam stuff prior to commenting above. The fact that Filippo was saying [CurveParam was a mistake in design](https://github.com/golang/go/issues/26776#issuecomment-497671740) makes me think investing in this route should be avoided?

**Comment by imirkin** [comment] 2021-02-17 22:12
Yeah, FWIW I tried it briefly. It doesn't work :) As pointed out by the issue, we need the value of "a" which is just missing. Oh well.

Will try with decred in a bit, should be pretty plug & play wrt my current impl. Hopefully.

**Comment by lestrrat** [comment] 2021-02-17 23:39
@eshepelyuk @imirkin has kindly implemented this functionality, but TBH there's not much else we can do to make sure that it is interoperable with other implementations. It looks correct, but somebody is going to have to test it on the field.

It's currently merged in the main branch, but if possible, I would like to wait releasing a new version until sometime passes, or until at least someone provides us with a clue that it actually works against implementations out there.

**Comment by lestrrat** [comment] 2021-02-17 23:44
Hmm, the merge didn't auto close the issue? oh well.

Closing for now, as the implementation was merged. Please file new issues if you find problems.

**Closed by lestrrat** 2021-02-17 23:44 UTC

**Comment by eshepelyuk** [comment] 2021-02-18 08:52
thanks
