### ISSUE TITLE
openid claim name constant does not follow standard oidc spec

### ISSUE THREAD

**Issue by zzycn003** [lestrrat-go/jwx#496] opened 2021-11-08 04:16 UTC
for openid.token_gen.go, the claim name constant should use snake_case rather than camelCase

per oidc spec https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

EmailVerifiedKey       = "emailVerified", should be "email_verifier"
PhoneNumberVerifiedKey = "phoneNumberVerified" , should be "phone_number_verified"
PreferredUsernameKey   = "preferredUsername", should be "preferred_username"

is it a bug ? thanks

**Comment by lestrrat** [comment] 2021-11-08 04:17
duplicate of #495. It just hasn't been released. please use v1.2.7 until I release the next version

**Closed** 2021-11-08 05:12 UTC
