### ISSUE TITLE
jwe header does not contain keyID

### ISSUE THREAD

**Issue by dragonfriend0013** [lestrrat-go/jwx#554] opened 2022-01-18 13:41 UTC
I am receiving a key set from a client through an API.  I use :

`keys, err := jwk.Parse(body)`

to parse the API body.  From this i am taking the first key and placing it into a new structure with the key, the public key (`pubKey, pubKeyErr := k.PublicKey()`) as well as its expiration

This new object is then used until its expiration.  I have confirmed that there is a keyId in the key object.

To encrypt my data, i am using:

`body, encErr := jwe.Encrypt(bodyBytes, encKey.Alg, encKey.PublicKey, jwa.A256GCM, jwa.Deflate)`

Upon looking at the resulting jwe header, i am getting something like:

```
{
  "alg":"ECDH-ES",
  "enc":"A256GCM",
  "epk":{
    "crv":"P-521",
    "kty":"EC",
    "x":"AEx2Clw6x2v6QgX7HT4paowgy5uROtyv1VAFrOYszookS19fZczSKVRucCxHBe04xUWSmhk1K8lMY0QByLzcVEpt",
    "y":"AKK1yBiSssY3fwSJTDAtotJ44PFgwBZsVZhF9OcUEbR2v0UlU6fEQy1jIVKPfyc6jvVDgrx0unCGqjfau4yQ5cVN"
  },
  "zip":"DEF"
}
```

My client needs to have the kid in the header, but i am unable to see how to get it placed in there.

i am on 1.2.17 of the jwx library

**Comment by lestrrat** [comment] 2022-01-18 23:14
Ah, that's a bug caused by an artifact of the past. Thank you for reporting.
Up until some point this library could not (easily) convert between JWKs and raw keys, and opted to use raw keys in most places. Raw keys such as ecdsa.PrivateKey does not have a notion of a key ID, and hence this information was dropped during message construction.

Fix coming up.

**Comment by lestrrat** [comment] 2022-01-18 23:54
@dragonfriend0013 can you please try the fix in #555. You should see the `kid` header in the unprotected headers section.

**Comment by lestrrat** [comment] 2022-01-19 00:49
@dragonfriend0013 oops, sorry, I missed something and the test are failing. Will let you know again.

**Comment by lestrrat** [comment] 2022-01-19 01:36
@dragonfriend0013 okay, all fixed. PTAL

**Comment by dragonfriend0013** [comment] 2022-01-19 13:42
I tested with the gh-554 branch and all is looking good

**Comment by lestrrat** [comment] 2022-01-19 23:08
Thanks, merged. I usually let these sit for a few days before releasing. Please `go get` directly from the repository for the time being.

**Closed** 2022-01-19 23:07 UTC
