### ISSUE TITLE
jws.VerifyWithJKU Passes on invalid signature

### ISSUE THREAD

**Issue by akhi4u** [lestrrat-go/jwx#140] opened 2020-03-05 19:52 UTC
I was using v0.9.0,  `jws.VerifyWithJKU()` validation worked fine. But once I updated to the newer version v0.9.1, it no longer validates the signature, returns no error. This is a serious issue. Could I get any help regarding this? 

Thank you.

**Comment by leandrorondon** [comment] 2020-03-09 15:55
I'm facing the same problem. The issue is in the `VerifyWithJWKSet` function - `err` variable is redeclared within `for` loop and end up returning a `nil` err.

**Comment by lestrrat** [comment] 2020-04-09 00:41
Sorry for warnocking this, but could you kindly provide with a reproducible test case?

**Comment by lestrrat** [comment] 2020-04-09 00:50
Hi, @akhi4u @leandrorondon 

It would be most helpful if you could kindly test PR #145, and again, sorry for the late response here

**Comment by lestrrat** [comment] 2020-04-11 08:13
I added tests, and I'm pretty certain I plugged the whole, so will merge #145 and close this issue.

**Closed** 2020-04-11 08:13 UTC
