### ISSUE TITLE
Getting "BAIL OUT" when running AsMap; error is nil

### ISSUE THREAD

**Issue by themattmck** [lestrrat-go/jwx#174] opened 2020-04-24 14:55 UTC
I'm getting "BAIL OUT" when I try to get my JWT as a map. Here's the code that I'm running below for debug purposes. As you can see in the output, I'm getting the token back with no error. The reason I'm trying to get it as a map is because I'm trying to extract attributes as well as use the map to put this token elsewhere in my code as the whole map. 

```golang
tkn := ctx.Value("token").(string)
parsedTkn, _ := jwt.ParseString(tkn)
mappedTkn, err := parsedTkn.AsMap(ctx)
fmt.Println(err)
fmt.Println(mappedTkn["scope"])
```

Here's the output: 
```
BAIL OUT
<nil>
openid profile email

**Comment by lestrrat** [comment] 2020-04-25 08:16
Are you saying that `jwx` or one of its dependencies is printing out "BAIL OUT"?

I haven't dug deeper, but as of this writing, `jwx` only depends on these four modules:

```
require (
  github.com/lestrrat-go/iter v0.0.0-20200422075355-fc1769541911
  github.com/pkg/errors v0.9.1
  github.com/stretchr/testify v1.5.1
  golang.org/x/tools v0.0.0-20200417140056-c07e33ef3290
)
```

... of which, only one is mine. at least as of lestrrat-go/iter@fc176954191104b7be24e78f6707f665ecf149b8, there's no string matching "BAIL" in the source code, and the same can be said about `jwx` @ b8ed9247539f5fdf22ddf2768c766836befb2a74 

So if my understanding about the problem is correct, you may want to update all dependencies to latest.

If I'm misunderstanding something, please include a _complete_ running code, preferably a Go test function so I can further understand the problem

**Comment by lestrrat** [comment] 2020-07-07 22:54
This issue has been left unanswered for a while, so I will be closing it. Please open a new issue if this is still a problem

**Closed by lestrrat** 2020-07-07 22:54 UTC
