### ISSUE TITLE
How to add do I include my public key/x5c in JWT header

### ISSUE THREAD

**Issue by cblims** [lestrrat-go/jwx#645] opened 2022-03-12 16:19 UTC
I'm currently trying to authenticate to an api which uses private_key_jwt, and they require the header x5c to be included in the header of the JWT. I've successfully signed a JWT token with private key (imported from PEM) and tried to manually include the certificate chain as key x5c. The key is not included in the final JWT. Does it filter the x5c key?

I can't find any examples how to include the certificate chain. Is it possible?

**Comment by lestrrat** [comment] 2022-03-12 22:54
I'm going to close this for now [because you have shown no code](https://github.com/lestrrat-go/jwx/blob/main/DISCLAIMERS.md#rule-2-please-provide-code-for-technical-issues
), but feel free to reopen when you have some code

**Comment by lestrrat** [comment] 2022-03-13 12:01
AAAAAAH, I see. I think I never used and I never really had anybody use _JWS_'s `x5c`, and I see what the problem is.
JWK's X509CertChain is a special type using `jwk.CertificateChain` object, but JWS is using `[]string`, and yes, I see why you would have problems.

For the time being, the way you wrote is correct, and I don't think I will be able to change that field for `v1` 
For `v2`, though, I think we should use the same sort of mechanism that already exists in `jwk`, and also optionally allow passing `jwk.Key` or the like to it.

---

> Is it easier to use jwk.ReadFile("public.pem",jwk.WithPEM(true)) and read the public cert into the header jws.X509CertChainKey?

Nah, if it needs to be turned into a string, I don't think it's worth it.

**Comment by cblims** [comment] 2022-03-13 12:12
Thanks!
Solved it by doing this:
```
	publicData, _ := ioutil.ReadFile(config.PublicKey)
	pemBlock, _ := pem.Decode(publicData)
	publicCert := b64.StdEncoding.EncodeToString(pemBlock.Bytes)

	var certs []string
	certs = append(certs, publicCert)

	hdrs := jws.NewHeaders()
	err = hdrs.Set(jws.X509CertChainKey, certs)
```

**Comment by lestrrat** [comment] 2022-03-14 03:26
It's somewhat more standardized in v2 now.

**Closed by lestrrat** 2022-03-14 03:26 UTC
