### ISSUE TITLE
Is there a single step to make jwk.Key into something storable by nosql?

### ISSUE THREAD

**Issue by student020341** [lestrrat-go/jwx#317] opened 2021-01-28 19:00 UTC
**Abstract**
I am building an identity provider for fun. Today I'm at the step where I can sign a JWT and have private and public rsa keys to store. I was able to get them into a json string and store them in mongo that way, but if I store them as an object (like map[string]interface{}) I will be able to query them more easily. I am having trouble with 2 methods I have come across and am unsure if I'm missing something. 

**Describe the proposed solution/change**
Ideally something like existing jwk.Key.AsMap, but I don't know how to describe what to change or what is wrong with the encoding. Even if I can iterate over every key, type check, and convert it would be nice to have some function that gave me something I could work with in 1 step. Something like an interface or string indexed interface, but without having to convert to and from json. 

**Analysis**
Currently I can get what I'm after by marshaling to and from json, but I know this cannot possibly be the intended solution:

```
	asJson, err := json.Marshal(key)
	if err != nil {
		...
	}
	var asMSI map[string]interface{}
	err = json.Unmarshal(asJson, &asMSI)
	if err != nil {
		...
	}
```

Which yields exactly what I want, a structure that ends up as an object in mongo:
```
map[e:AQAB kid:upXClk25ZYicG0uupX5Zn_NDCoIi4NzwbFiVkgxmlNw kty:RSA n:oXDFdy2BcGWKbL4RoeivwqCMBKbvTlnFmNnqXS9YfQnxtbY5omXkPMg1LxrDl6GX3A5qiE1M1SDtWrxDepXL9FfliH9ONmkcCPJ8mIw5RDDWzTC39M5h8FErh5-SvLIrB067rXx_OspW2xWRhi7oGO9mYN_i3Q6YPAZbWobfiRb1pOH4DsTg7Rk8tWixUWa8Yto3g0Ovu5didxG3MxZy1Zzof_10iULkFDq0AeXvOaMDxIrEQTc-vI-RsCk8Yp1OArXpakcaHobJN9i9G4rm53OMopxKMD7_w9Y3sS4nqRuMEmiVh7JMQjowYyCJ90IVGxg9Gt6NdtS5yout1yO_bw]
```

I have also tried AsMap, but that gave me either broken strings or byte arrays that didn't convert to strings, like this:
```
 n:▒b▒▒M▒J▒%I▒▒▒▒▒C▒▒▒
```

**Additional context**
This isn't really important, I can workaround it with the marshal/unmarshal, and I hope it's something simple I'm misunderstanding about the format 'AsMap' is giving. It's definitely a map, and it has the right indices, but the values are unreadable from either my console or when inserted in mongo.

**Comment by lestrrat** [comment] 2021-01-28 22:06
"n" in the example you gave is binary data -- a series of bits that describe a large prime number. So it's []byte, and they don't represent a series of readable characters. In JSON form, they are encoded into base64. But because we may do calculations or create "raw" keys from it, it's easier to store them as binary.

That is why the values in a key are "broken". They are not supposed to be strings. But you are free to do any conversion yourself, so the short answer is to fix the data yourself from whatever you fetch the data with (AsMap, Iterate, etc)

Getting back to the original problem though, I don't understand why you need the raw map to insert into a nosql store? I would personally just store the key in JSON format, as it is accurate, and it produces output that can be read from any language, and not just go. 

Anyways, this is not an "issue" with the library, so I'm closing it for the time being. Please feel free to reopen if you think there's a feature missing that should be provided.

**Closed by lestrrat** 2021-01-28 22:06 UTC

**Comment by lestrrat** [comment] 2021-01-28 22:16
Hey, I'm sorry, I completely overlooked the first part of your response. will respond in my next reply

**Comment by lestrrat** [comment] 2021-01-28 22:24
The explanation about `n` being a []byte still stands. So the problem is, just converting them to a serialized form.
One way is just to use encoding/json
```go
var m interface{}
json.Unmarshal(jsonBytes, &m)
```
This will store values like `n` as strings.

Or, if you want to start with a `jwk.Key`, you can use `AsMap` or `Iterate`

```go
m := key.AsMap(ctx)
for k, v := range m {
   if k == "n" {
      m[k] = baset64.RawURLEncoding.EncodeString([]byte(v))
  }
  ...
}
```

Or use `Iterate` instead of `AsMap`.

In either case, though, the question is: "What if the key contains arbitrary nested data structures?" for example
```json
{ "n", "....", "myawesomedata": { "nested": { "deep": "inside" } } }
```
There *is* a possibility that in Go, "mywesomedata" is stored as something other than a pure JSON hash. Would you have complete control over data coming in? maybe, maybe not I wouldn't know, and either way you are going to have to make a judgement call as to how much effort you put into working "correctly" with arbitrary JWKs.

The ONE serialization format that is compatible with everything JWK is JSON. You HAVE to be able to serialize to JSON. So you are completely safe from any assumptions. Therefore, you should just either dump JSON into the store, or use a method that does not go through a representation like JWK, and load the data separately into a `map[]` via json.Unmarshal

**Comment by student020341** [comment] 2021-01-28 22:27
Hey, no problem. I ran into too many knowledge gaps to proceed with my project at this time, so I'm going to just use okta or something instead of building an identity provider. I may try again in the future when I have a better understanding of jwt/jwk. 

Thanks anyway for answering some of those questions! To answer the nosql storage question, that was just for query purposes. If it's an object instead of a json string, I can filter for "keys.public.kid" instead of grabbing them all from the database and building a key set. Maybe that doesn't make sense, it's a thought without much foundation behind it.
